apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/podinfo

patches:
  - path: podinfo/version.yaml
  - path: podinfo/_tracing.yaml

transformers:
  - registry.yaml
