apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
      - name: podinfod
        env:
        - name: REGION
          value: EU
        - name: GDPR_ENABLED
          value: true
